### ISSUE TITLE
First Stage: A POA bridge supporting verify darwinia events

### ISSUE THREAD

**Issue by WoeOm** [darwinia-network/darwinia-bridge-on-ethereum#1]
- [x] A POA Bridge with trust setup. Any authority can submit a MMR.
- [x] A guard system that can verify correctness of  header MMR, if not can stop bridge after specific darwinia block number.
- [x] Only superviser(a multisig) can restore from pause status and clean wrong submitted mmr.

Any submitted MMR will need to wait for a period(number of ethereum blocks) before confirm, in this period, other authority can challenge and pause.

Any authority can pause the bridge by submitting a pause tx(with info of the latest submitted valid darwinia header he think, any mmr after this header can not be used for verify darwinia events). Other authority can continue pause with older headers.

Only admin(multsig) can restore from pause and do clean stuffs.

A cooperating backing module for issue and redeem protocol

**Comment by HackFisher** [comment]
The description is more close and for Ethereum=>Darwinia Bridge, we are going to use EsdsaAuthority(Fraud proof) to replace POA and work as proxy for grandpa authories.
