### ISSUE TITLE
why we don't need to filter the duplicated signatures

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia-bridge-on-ethereum#17]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/01e19b1067bf88c24946fecdeef01c2fa31a179d/contracts/Relay.sol#L292
if all the signatures are signed by the same authority, can this condition be satisfied?

**Comment by WoeOm** [comment]
this is a serious issue, ill fix it
