### ISSUE TITLE
Why the byte order is not same?

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridge-on-ethereum#20]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/common/Scale.sol#L115

https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/common/Scale.sol#L93

**Comment by HackFisher** [comment]
@wuminzhe @WoeOm Could you help explain this, related to Scale codec.

**Comment by wuminzhe** [comment]
the second may be wrong.

**Comment by wuminzhe** [comment]
uint in scale codec is encoded in little endian

**Comment by WoeOm** [comment]
`return uint32(nonce.toBytes4(0)); ` is out-of-date code,  has been removed.
