### ISSUE TITLE
Opt

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridge-on-ethereum#21]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/Relay.sol#L325

https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/common/Bytes.sol#L15

Using lib function may be more efficient.

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/Relay.sol#L30

`nonce` should be the last slot for gas saving.

**Comment by WoeOm** [comment]
> https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/Relay.sol#L30
> 
> `nonce` should be the last slot for gas saving.

equals  use 1193 gas
assertBytesEq use 1866gas

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/Relay.sol#L102

Params`eventsProofStr` could be passed using `bytes[]` directly instead of `decodeReceiptProof` to decode it.
It is worth to test the gas cost.

**Comment by WoeOm** [comment]
> https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/common/Scale.sol#L115
> 
> If it is encoded by uint (LE).
> 
> ```
>     function decodeU64(Data memory data) internal pure returns(uint64 value) {
>         value = uint64(decodeU32(data));
>         value |= (uint64(decodeU32(data)) << 32);
>     }
>     function decodeU128(Data memory data) internal pure returns(uint128 value) {
>         value = uint128(decodeU64(data));
>         value |= (uint128(decodeU64(data)) << 64);
>     }
> ```
> 
> Using `Input.decodeU128` may be better instead of `reverseBytes16`
> 
> @wuminzhe Please help to check the `value` is not encoded by Scale Format.

decodeU128 gas used 26639
reverseBytes16 gas used 26115

**Comment by WoeOm** [comment]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/a48104463b6096aa0c432672ec1f0054bbd87676/contracts/MMR.sol#L154

heightAt - 3,765 Gas

This method in the loop func and cost a lot of gas.
