### ISSUE TITLE
Might need to check block number against BlockHeader

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-bridge-on-ethereum#26]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/1ad5d943fb669d80f8d95e3df561b58a657a7bbf/contracts/Relay.sol#L198

https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/1ad5d943fb669d80f8d95e3df561b58a657a7bbf/contracts/TokenIssuing.sol#L95

**Comment by WoeOm** [comment]
#27
