### ISSUE TITLE
Merkle Proof/Trie Proof Verification using Precompiled Contracts(EIP-152)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-bridge-on-ethereum#4]
https://eips.ethereum.org/EIPS/eip-152

Related #3

**Comment by WoeOm** [comment]
https://github.com/darwinia-network/darwinia-bridge-on-ethereum/blob/e834d9dc37a41afd893c0803eeff8252865e44e0/contracts/Blake2b.sol#L84
